import { randomBytes } from "node:crypto";
import { access, mkdir, open, readFile } from "node:fs/promises";
import path from "node:path";

const DEFAULT_MANAGEMENT_PORT = 9820;
const CC_CONNECT_VERSION = "1.5.0";
const CONFIG_MARKER = "# Managed entrypoint generated by OpenQuantum";
const DEFAULT_PROJECT_NAME = "openquantum";
const QUICK_SETUP_PLATFORMS = new Set(["feishu", "weixin", "yuanbao"]);

function quoted(value) {
  return JSON.stringify(value);
}

function projectPath(projectRoot, ...parts) {
  return path.join(path.resolve(projectRoot), ...parts);
}

export function resolveCcConnectPaths(projectRoot) {
  const root = path.resolve(projectRoot);
  const stateRoot = projectPath(root, ".openquantum", "cc-connect");
  return Object.freeze({
    projectRoot: root,
    stateRoot,
    configPath: path.join(stateRoot, "config.toml"),
    acpConfigPath: projectPath(
      root,
      "runtime",
      "openquantum",
      "cc-connect",
      "cordis.yml",
    ),
    ccConnectBin: projectPath(root, "node_modules", ".bin", "cc-connect"),
    acpBin: projectPath(root, "node_modules", ".bin", "dsh-acp-demo"),
  });
}

export function buildCcConnectPlatformSetupArgs(projectRoot, platform, extraArgs = []) {
  if (!QUICK_SETUP_PLATFORMS.has(platform)) {
    throw new TypeError(`不支持的 CC Connect 快速配置：${platform}`);
  }
  const paths = resolveCcConnectPaths(projectRoot);
  return [
    platform,
    "setup",
    "-config",
    paths.configPath,
    "-project",
    DEFAULT_PROJECT_NAME,
    ...extraArgs,
  ];
}

export function renderCcConnectConfig(projectRoot, managementToken) {
  if (typeof managementToken !== "string" || managementToken.length < 24) {
    throw new TypeError("CC Connect management token is invalid");
  }
  const paths = resolveCcConnectPaths(projectRoot);
  return `${CONFIG_MARKER}
# Platform credentials are added later through the local CC Connect admin UI.
language = "zh"

[log]
level = "info"

[management]
enabled = true
port = ${DEFAULT_MANAGEMENT_PORT}
token = ${quoted(managementToken)}
cors_origins = []

[[projects]]
name = "openquantum"
reset_on_idle_mins = 30

[projects.agent]
type = "acp"

[projects.agent.options]
work_dir = ${quoted(paths.projectRoot)}
cmd = ${quoted(paths.acpBin)}
args = ["--config", ${quoted(paths.acpConfigPath)}]
display_name = "OpenQuantum"
`;
}

async function exists(filename) {
  try {
    await access(filename);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

function managementPort(configText) {
  const section = configText
    .split(/^\[management\]\s*$/m)[1]
    ?.split(/^\[/m)[0];
  const configured = section?.match(/^port\s*=\s*(\d+)\s*$/m)?.[1];
  const port = Number(configured ?? DEFAULT_MANAGEMENT_PORT);
  return Number.isInteger(port) && port > 0 && port <= 65535
    ? port
    : DEFAULT_MANAGEMENT_PORT;
}

function managementToken(configText) {
  const section = configText
    .split(/^\[management\]\s*$/m)[1]
    ?.split(/^\[/m)[0];
  const encoded = section?.match(/^token\s*=\s*("(?:[^"\\]|\\.)*")\s*$/m)?.[1];
  if (!encoded) return null;
  try {
    return JSON.parse(encoded);
  } catch {
    return null;
  }
}

function configuredPlatforms(configText) {
  const platforms = [];
  const blocks = configText.split(/^\[\[projects\.platforms\]\]\s*$/m).slice(1);
  for (const block of blocks) {
    const type = block.match(/^type\s*=\s*["']([^"']+)["']\s*$/m)?.[1];
    if (type && !platforms.includes(type)) platforms.push(type);
  }
  return platforms;
}

export async function probeCcConnectManagement(port, options = {}) {
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  const timeoutMs = options.timeoutMs ?? 400;
  if (typeof fetchImpl !== "function") return false;
  try {
    const response = await fetchImpl(
      `http://127.0.0.1:${port}/api/v1/status`,
      {
        headers: options.token
          ? { authorization: `Bearer ${options.token}` }
          : undefined,
        signal: AbortSignal.timeout(timeoutMs),
      },
    );
    return response.ok;
  } catch {
    return false;
  }
}

export async function readCcConnectStatus(projectRoot, options = {}) {
  const paths = resolveCcConnectPaths(projectRoot);
  const installed = await Promise.all([
    exists(paths.ccConnectBin),
    exists(paths.acpBin),
    exists(paths.acpConfigPath),
  ]).then((checks) => checks.every(Boolean));
  if (!(await exists(paths.configPath))) {
    return Object.freeze({
      id: "cc-connect",
      displayName: "CC Connect",
      version: CC_CONNECT_VERSION,
      state: installed ? "not-configured" : "not-installed",
      installed,
      configured: false,
      running: false,
      managementUrl: `http://127.0.0.1:${DEFAULT_MANAGEMENT_PORT}`,
      configPath: ".openquantum/cc-connect/config.toml",
      platformTypes: [],
      sourceUrl: "https://github.com/chenhg5/cc-connect",
      commands: {
        setup: "npm run cc-connect:setup",
        start: "npm run cc-connect:start",
        web: "npm run cc-connect:web",
        status: "npm run cc-connect:status",
      },
    });
  }

  const configText = await readFile(paths.configPath, "utf8");
  const port = managementPort(configText);
  const platforms = configuredPlatforms(configText);
  const running = installed && await (options.probe ?? probeCcConnectManagement)(port, {
    token: managementToken(configText),
  });
  return Object.freeze({
    id: "cc-connect",
    displayName: "CC Connect",
    version: CC_CONNECT_VERSION,
    state: running
      ? "running"
      : platforms.length > 0
      ? "configured"
      : "needs-platform",
    installed,
    configured: true,
    running,
    managementUrl: `http://127.0.0.1:${port}`,
    configPath: ".openquantum/cc-connect/config.toml",
    platformTypes: platforms,
    sourceUrl: "https://github.com/chenhg5/cc-connect",
    commands: {
      setup: "npm run cc-connect:setup",
      start: "npm run cc-connect:start",
      web: "npm run cc-connect:web",
      status: "npm run cc-connect:status",
    },
  });
}

export async function ensureCcConnectConfig(projectRoot, options = {}) {
  const paths = resolveCcConnectPaths(projectRoot);
  const tokenFactory = options.tokenFactory ?? (() => randomBytes(24).toString("hex"));
  await mkdir(paths.stateRoot, { recursive: true, mode: 0o700 });
  const token = tokenFactory();
  const config = renderCcConnectConfig(projectRoot, token);
  let handle;
  try {
    handle = await open(paths.configPath, "wx", 0o600);
    await handle.writeFile(config, "utf8");
    await handle.sync();
  } catch (error) {
    if (error?.code !== "EEXIST") throw error;
    return Object.freeze({ created: false, ...(await readCcConnectStatus(projectRoot, options)) });
  } finally {
    await handle?.close();
  }
  return Object.freeze({ created: true, ...(await readCcConnectStatus(projectRoot, options)) });
}
