export const OPENQUANTUM_BRAND = Object.freeze({
  name: "OpenQuantum",
  tagline: Object.freeze({
    en: "Quantum computing, right at your fingertips",
    zh: "量子计算，就在指尖",
    ja: "量子コンピューティングを、あなたの手に",
    ko: "손끝에서 시작하는 양자 컴퓨팅",
    es: "La computación cuántica, al alcance de tu mano",
    fr: "L’informatique quantique à portée de main",
    de: "Quantencomputing zum Greifen nah",
    pt: "Computação quântica ao seu alcance",
    ru: "Квантовые вычисления у вас под рукой",
    ar: "الحوسبة الكمومية بين يديك",
  }),
  mark: Object.freeze({
    faviconPath: "/favicon.svg",
    icon192Path: "/openquantum/icon-192.png",
    icon512Path: "/openquantum/icon-512.png",
    inverseLockupPath: "/openquantum/lockup-inverse.svg",
    inverseSvgPath: "/openquantum/mark-inverse.svg",
    lockupPath: "/openquantum/lockup.svg",
    svgPath: "/openquantum/mark.svg",
  }),
  colors: Object.freeze({
    accent: "#6747f4",
    background: "#f7fbff",
    ink: "#061f38",
    primary: "#00cddd",
  }),
});
