import sys
from pathlib import Path
from importlib.metadata import version
sys.path.insert(0, str(Path(__file__).resolve().parents[4] / "src/lib"))
from science_bridge import execute
from quantum_reference import pauli_matrix


def compute(v):
    import numpy as np
    from paulie import get_pauli_string
    if version("paulie") != "0.2.3":
        raise ValueError("Unexpected PauLie version; restore the frozen environment")
    n = v["numQubits"]
    generators = [get_pauli_string(word) for word in v["generators"]]
    words = {str(p): p for p in generators}
    queue = list(generators)
    for current in queue:
        for generator in generators:
            if not current.commutes_with(generator):
                product = current @ generator
                word = str(product)
                if word not in words:
                    words[word] = product
                    queue.append(product)
    closure = sorted(words)
    # Independently build the real Lie span of skew-Hermitian matrices. Adjoint
    # action by the original generators generates the full Lie closure.
    matrices = [1j * pauli_matrix(word) for word in v["generators"]]
    basis_matrices, basis_vectors = [], []
    def real_vector(matrix):
        return np.concatenate([matrix.real.ravel(), matrix.imag.ravel()])
    def residual(matrix):
        vector = real_vector(matrix)
        if basis_vectors:
            basis = np.asarray(basis_vectors)
            for _ in range(2):
                vector -= (basis @ vector) @ basis
        return vector
    def add(matrix):
        vector = residual(matrix)
        norm = np.linalg.norm(vector)
        if norm > 1e-10:
            vector /= norm
            half = vector.size // 2
            basis_vectors.append(vector)
            basis_matrices.append((vector[:half] + 1j * vector[half:]).reshape(2 ** n, 2 ** n))
    for matrix in matrices:
        add(matrix)
    for current in basis_matrices:
        for generator in matrices:
            add(generator @ current - current @ generator)
    span_error = max(float(np.linalg.norm(residual(1j * pauli_matrix(word)))) for word in closure)
    if len(closure) != len(basis_matrices) or span_error > 1e-8:
        raise ValueError("PauLie closure disagrees with the independent dense Lie span")
    collection = get_pauli_string(v["generators"])
    classified_dimension = collection.get_dla_dim()
    if classified_dimension != len(closure):
        raise ValueError("PauLie classification dimension disagrees with its explicit closure")
    return {"dimension": len(closure), "referenceDimension": len(basis_matrices), "classification": collection.get_algebra(),
        "fullSpecialUnitaryDimension": 4 ** n - 1, "generatesFullSpecialUnitary": len(closure) == 4 ** n - 1,
        "closure": closure, "maxSpanResidual": span_error, "bitOrder": "left-to-right q0,q1,..."}, [
        "The Lie algebra is the real span generated by i times each supplied Pauli word, with independent real control coefficients. Identity/global phase generators are excluded.",
        "Classification names may use isomorphic algebras, e.g. so(3) for su(2) or so(6) for su(4); dimensions and the represented span are independently checked, not the full abstract classification.",
        "Full su(2^n) under these assumptions does not establish finite-depth ansatz expressibility, trainability, pulse reachability or hardware controllability.",
        "Bounded algebra calculation and dense checks only; no central scientific acceptance."]


execute(compute)
